In [3]:
import numpy as np

arr = np.arange(50).reshape(10, 5)
print(arr)

# Selecting first 5 rows of the 4th column (Note: Since the array has only 5 columns, this will raise an index error)
try:
    a = arr[:5, 4]
    print(a)
except IndexError as e:
    print("IndexError:", e)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[ 4  9 14 19 24]


In [15]:
%pip install tabulate


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.1 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
from tabulate import tabulate

In [30]:
arr = np.arange(70).reshape(7, 10)
print(arr)
print(arr.shape)
a = arr[5, :6]
print(a)
print(tabulate(arr, tablefmt="grid"))


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]
(7, 10)
[50 51 52 53 54 55]
+----+----+----+----+----+----+----+----+----+----+
|  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 |
+----+----+----+----+----+----+----+----+----+----+
| 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 |
+----+----+----+----+----+----+----+----+----+----+
| 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 |
+----+----+----+----+----+----+----+----+----+----+
| 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 |
+----+----+----+----+----+----+----+----+----+----+
| 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 |
+----+----+----+----+----+----+----+----+----+----+
| 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 |
+----+----+----+----+----+----+----+----+----+----+
| 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 |
+----+----+-